# fix terminal colors on wsl
set -g default-terminal "screen-256color"

# rekeybind the command key to ctrl+space
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# split panes using | and -
bind | split-window -c '#{pane_current_path}' -h
bind - split-window -c '#{pane_current_path}' -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
set -g @yank_action "copy-pipe"

#bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'clip.exe'
#bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'clip.exe'

set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm'
